version: '3'

services:
  task_server:
    build: .
    image: task_server
    ports:
      - '4000:4000'
    depends_on:
      - db_mongo
    volumes:
      - .:/usr/src/task_server 

  db_mongo:
    image: mongo
    ports:
      - '27017:27017'
