version: '3'

services:
  task_server:
    container_name: task_server_test
    networks:
      - test
    environment:
      - MONGODB_URL=mongodb://user:password@db_mongo:27017/tasks_test?authSource=admin
      - NODE_ENV=test
    command: sh -c "npm install && npm run test"

  db_mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - test
    volumes:
      - mongo_data_test:/data/db

volumes:
  mongo_data_test:

networks:
  test:
    driver: bridge