version: '3'

services:
  task_server:
    container_name: task_server_development
    networks:
      - development
    environment:
      - MONGODB_URL=mongodb://user:password@db_mongo:27017/tasks_dev?authSource=admin
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"

  db_mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - development
    volumes:
      - mongo_data_dev:/data/db

volumes:
  mongo_data_dev:

networks:
  development:
    driver: bridge