version: '3'

services:
  task_server:
    container_name: task_server_production
    networks:
      - production
    environment:
      - MONGODB_URL=mongodb://user:password@db_mongo:27017/tasks_prod?authSource=admin
      - NODE_ENV=production
    command: sh -c "npm install --production && npm start"

  db_mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - production
    volumes:
      - mongo_data_prod:/data/db

volumes:
  mongo_data_prod:

networks:
  production:
    driver: bridge